"""Pydantic models for `.dlm` frontmatter.

Every model is `extra="forbid"` and `frozen=True` — strict validation and
immutable values. Default values must match the shape produced by
`tests/fixtures/dlm_factory.py` so round-trips are stable.

Sprint 12b introduces a versioned dispatcher in `dlm.doc.versioned`;
until then this module ships only the v1 `DlmFrontmatter`.
"""

from __future__ import annotations

import re
from typing import Final, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

# Crockford base32 alphabet used by ULID: 0-9, A-Z minus I L O U.
_ULID_RE: Final[re.Pattern[str]] = re.compile(r"^[0-9A-HJ-KM-NP-TV-Z]{26}$")

CURRENT_SCHEMA_VERSION: Final[int] = 1
"""Schema version this parser implements.

Sprint 12b extends this via the migration framework; new fields bump the
version and register a migrator in the same commit (enforced by a test).
"""


class TrainingConfig(BaseModel):
    """Training-time knobs. `auto` values are resolved by the hardware doctor."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    adapter: Literal["lora", "qlora"] = "lora"
    lora_r: int = Field(8, ge=1, le=256)
    lora_alpha: int = Field(16, ge=1)
    lora_dropout: float = Field(0.05, ge=0.0, le=0.5)
    target_modules: Literal["auto"] | list[str] = "auto"
    sequence_len: int = Field(2048, ge=64, le=32768)
    micro_batch_size: Literal["auto"] | int = "auto"
    grad_accum: Literal["auto"] | int = "auto"
    learning_rate: float = Field(2e-4, gt=0.0)
    num_epochs: int = Field(3, ge=1)
    optimizer: Literal["adamw_torch", "adamw_bnb_8bit", "paged_adamw_8bit"] = "adamw_torch"
    lr_scheduler: Literal["cosine", "linear", "constant"] = "cosine"
    warmup_ratio: float = Field(0.1, ge=0.0, le=0.5)
    seed: int = 42

    @field_validator("micro_batch_size", "grad_accum")
    @classmethod
    def _validate_auto_or_positive(cls, v: int | str) -> int | str:
        if v == "auto":
            return v
        if not isinstance(v, int) or v < 1:
            raise ValueError(f"must be a positive int or 'auto', got {v!r}")
        return v


class ExportConfig(BaseModel):
    """Export-time defaults."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    default_quant: Literal["Q4_K_M", "Q5_K_M", "Q6_K", "Q8_0"] = "Q4_K_M"
    # Optional per-document sampling overrides. When set, the Modelfile
    # emits `PARAMETER temperature <v>` / `PARAMETER top_p <v>` in place
    # of the dialect default — a Q&A document prefers temperature=0.2,
    # a creative one prefers 0.9. `None` keeps the dialect default
    # (audit-04 Q5).
    default_temperature: float | None = Field(None, gt=0.0, le=2.0)
    default_top_p: float | None = Field(None, gt=0.0, le=1.0)


# Named factories so mypy can type-check the field defaults correctly.
def _default_training() -> TrainingConfig:
    return TrainingConfig()


def _default_export() -> ExportConfig:
    return ExportConfig()


class DlmFrontmatter(BaseModel):
    """Top-level frontmatter: the YAML block between `---` delimiters.

    `dlm_id` is a canonical 26-character ULID. It is assigned by
    `dlm init` (Sprint 13) and never regenerated by the parser.
    `base_model` is either a registry key (e.g. `qwen2.5-1.5b`) or an
    `hf:org/name` escape hatch — the registry (Sprint 06) validates the
    actual lookup; this module only validates that the string is non-empty.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    dlm_id: str
    dlm_version: int = CURRENT_SCHEMA_VERSION
    base_model: str = Field(..., min_length=1)
    training: TrainingConfig = Field(default_factory=_default_training)
    export: ExportConfig = Field(default_factory=_default_export)
    system_prompt: str | None = None

    @field_validator("dlm_id")
    @classmethod
    def _validate_ulid(cls, v: str) -> str:
        if not _ULID_RE.fullmatch(v):
            raise ValueError(
                f"dlm_id must be a 26-char Crockford base32 ULID, got {v!r}",
            )
        return v

    @field_validator("dlm_version")
    @classmethod
    def _validate_version(cls, v: int) -> int:
        # The parser enforces the *current* version; fields from future
        # versions would fail extra="forbid" above. We just refuse
        # obviously wrong values here.
        if v < 1:
            raise ValueError(f"dlm_version must be ≥1, got {v}")
        return v
