"""HuggingFace Hub sink — push a `.dlm.pack` to a model repo, pull it back.

Pushes land in a user-owned repo (personal namespace like
`hf:username/foo` needs only an HF account and a write token; no
organization membership or review required). An auto-generated
README.md is uploaded alongside, tagged `library_name: dlm` so HF's
filters can surface dlm-format repos.

Authentication comes from the standard HF paths: `huggingface_hub`
reads `$HF_TOKEN` or `~/.cache/huggingface/token` automatically. We
don't handle tokens directly — if the user hasn't logged in, the hub
library's own error surfaces cleanly through our `SinkError` wrapper.

`huggingface_hub` is already a runtime dep (for base-model downloads),
so this sink has zero additional install cost.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from dlm.share.errors import SinkError

_LOG = logging.getLogger(__name__)

_PACK_FILENAME = "adapter.dlm.pack"
_README_FILENAME = "README.md"

ProgressCallback = Callable[[int, int], None] | None


@dataclass(frozen=True)
class HFUploadSummary:
    """Return value from `push_hf`. Used for CLI success messages."""

    repo_id: str  # e.g. "myuser/my-adapter"
    pack_url: str
    readme_url: str


def push_hf(
    pack_path: Path,
    repo_id: str,
    *,
    private: bool = False,
    readme_fields: dict[str, str] | None = None,
    progress: ProgressCallback = None,
) -> HFUploadSummary:
    """Upload `pack_path` to `hf:<repo_id>`. Creates the repo if missing.

    `readme_fields` drives the autogenerated card: typical keys are
    `dlm_id`, `base_model`, `adapter_version`, `license`. Raises
    `SinkError` on any HF Hub error (auth, network, permissions).
    """
    if not pack_path.is_file():
        raise SinkError(f"pack file missing: {pack_path}")

    # Deferred import — huggingface_hub pulls a lot of transitive deps.
    try:
        from huggingface_hub import create_repo, upload_file
        from huggingface_hub.utils import HfHubHTTPError  # type: ignore[attr-defined]
    except ImportError as exc:  # pragma: no cover — huggingface_hub is a runtime dep
        raise SinkError("huggingface_hub not installed") from exc

    # Create the repo if it doesn't exist; creating an existing repo is
    # idempotent under `exist_ok=True`.
    try:
        create_repo(
            repo_id=repo_id,
            repo_type="model",
            private=private,
            exist_ok=True,
        )
    except HfHubHTTPError as exc:
        raise SinkError(
            f"hf push: failed to ensure repo {repo_id!r}: {exc}"
        ) from exc

    # Upload the pack.
    if progress is not None:
        progress(0, pack_path.stat().st_size)
    try:
        pack_url = upload_file(
            path_or_fileobj=str(pack_path),
            path_in_repo=_PACK_FILENAME,
            repo_id=repo_id,
            repo_type="model",
            commit_message=f"Upload {_PACK_FILENAME} via dlm push",
        )
    except HfHubHTTPError as exc:
        raise SinkError(f"hf push: upload failed: {exc}") from exc

    if progress is not None:
        size = pack_path.stat().st_size
        progress(size, size)

    # Generate + upload the README.
    readme = _render_readme(repo_id, readme_fields or {})
    try:
        readme_url = upload_file(
            path_or_fileobj=readme.encode("utf-8"),
            path_in_repo=_README_FILENAME,
            repo_id=repo_id,
            repo_type="model",
            commit_message="Upload README.md via dlm push",
        )
    except HfHubHTTPError as exc:
        raise SinkError(f"hf push: README upload failed: {exc}") from exc

    _LOG.info("hf push: %s → %s", pack_path, repo_id)
    return HFUploadSummary(
        repo_id=repo_id,
        pack_url=str(pack_url),
        readme_url=str(readme_url),
    )


def pull_hf(
    repo_id: str,
    out_path: Path,
    *,
    progress: ProgressCallback = None,
) -> int:
    """Download the pack from `hf:<repo_id>` to `out_path`. Returns bytes.

    Expects the pack to be named `adapter.dlm.pack` in the repo (the
    name we upload under). Raises `SinkError` on any HF Hub error.
    """
    try:
        from huggingface_hub import hf_hub_download
        from huggingface_hub.utils import HfHubHTTPError  # type: ignore[attr-defined]
    except ImportError as exc:  # pragma: no cover
        raise SinkError("huggingface_hub not installed") from exc

    out_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        downloaded = hf_hub_download(
            repo_id=repo_id,
            filename=_PACK_FILENAME,
            repo_type="model",
        )
    except HfHubHTTPError as exc:
        raise SinkError(f"hf pull: download failed for {repo_id!r}: {exc}") from exc

    # `hf_hub_download` lands the file in HF's cache; copy to the
    # caller's out_path so the caller controls the lifetime.
    import shutil

    shutil.copy2(downloaded, out_path)
    size = out_path.stat().st_size
    if progress is not None:
        progress(size, size)
    _LOG.info("hf pull: %s → %s (%d bytes)", repo_id, out_path, size)
    return size


def _render_readme(repo_id: str, fields: dict[str, str]) -> str:
    """Emit the canonical README.md for a dlm-format HF model repo."""
    dlm_id = fields.get("dlm_id", "(unknown)")
    base_model = fields.get("base_model", "(unknown)")
    adapter_version = fields.get("adapter_version", "(unknown)")
    license_note = fields.get("license", "See the base model's license.")

    return f"""---
library_name: dlm
tags:
  - dlm
  - lora-adapter
---

# {repo_id}

Packed via [`dlm`](https://github.com/tenseleyFlow/DocumentLanguageModel)
— a text file that becomes a locally-trained LoRA adapter.

## Contents

- **`{_PACK_FILENAME}`** — the signed, content-addressed bundle
  (`.dlm.pack`). Includes the source `.dlm` document, the trained
  adapter, the training-state sidecar, and a per-run manifest.

## Identity

| Field | Value |
|---|---|
| `dlm_id` | `{dlm_id}` |
| `base_model` | `{base_model}` |
| `adapter_version` | `{adapter_version}` |

## License

{license_note}

## Install

```bash
dlm pull hf:{repo_id}
```

This downloads the pack + unpacks it into your local `dlm` store,
ready for `dlm prompt`, `dlm train --resume`, or `dlm export`.
"""
