"""`Modelfile` generator — the thing `ollama create` consumes.

Assembles a complete Modelfile from:

- The `ExportPlan` (quant, merged flag)
- The `BaseModelSpec` (for license + registry metadata in header)
- The adapter directory (source of truth for stops + chat template
  per Sprint 12b's tokenizer contract — audit F06)
- The user's system prompt from frontmatter, if any

Output shape is fixed (see Sprint 12 spec). Stops are always emitted
— missing stops cause runaway generation (findings §9).

Security: `SYSTEM "..."` content is shell-escaped via `shlex.quote`
to defend against `"` / newline injection in user-supplied prompts.
The Modelfile's `SYSTEM` directive treats its string as a quoted
literal, so a naïve string interpolation would be exploitable.
"""

from __future__ import annotations

import json
import shlex
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from dlm.export.ollama.errors import ModelfileError
from dlm.export.ollama.template_registry import DialectTemplate, get_template

if TYPE_CHECKING:
    from dlm.base_models import BaseModelSpec
    from dlm.export.plan import ExportPlan


@dataclass(frozen=True)
class ModelfileContext:
    """Everything `render_modelfile` needs to produce one Modelfile."""

    spec: BaseModelSpec
    plan: ExportPlan
    adapter_dir: Path
    base_gguf_name: str  # e.g., "base.Q4_K_M.gguf" or "merged.Q4_K_M.gguf"
    adapter_gguf_name: str | None  # None on --merged path
    dlm_id: str
    adapter_version: int
    system_prompt: str | None = None
    source_dlm_path: Path | None = None
    dlm_version: str = "dev"


def render_modelfile(ctx: ModelfileContext) -> str:
    """Return the full Modelfile text.

    Raises `ModelfileError` when the adapter dir is missing metadata
    required for a correct Modelfile (template file, tokenizer config).
    """
    dialect = ctx.spec.template
    template_row = get_template(dialect)

    stops = _resolve_stops(ctx.adapter_dir, template_row)
    header = _build_header(ctx)
    from_line = f"FROM ./{ctx.base_gguf_name}"
    adapter_line = f"ADAPTER ./{ctx.adapter_gguf_name}" if ctx.adapter_gguf_name else None
    template_block = _build_template_block(template_row)
    param_lines = _build_param_lines(
        stops=stops,
        temperature=template_row.default_temperature,
        top_p=template_row.default_top_p,
    )
    system_line = _build_system_line(ctx.system_prompt)
    license_line = _build_license_line(ctx.spec)

    # Assemble with blank-line separators for readability; the Ollama
    # parser doesn't care about whitespace between directives.
    parts: list[str] = [header, "", from_line]
    if adapter_line is not None:
        parts.append(adapter_line)
    parts.extend(["", template_block, ""])
    parts.extend(param_lines)
    if system_line is not None:
        parts.extend(["", system_line])
    if license_line is not None:
        parts.extend(["", license_line])
    # Trailing newline: every text file.
    return "\n".join(parts) + "\n"


# --- header ---------------------------------------------------------------


def _build_header(ctx: ModelfileContext) -> str:
    now = datetime.now(UTC).replace(tzinfo=None, microsecond=0).isoformat()
    lines = [
        f"# Generated by dlm {ctx.dlm_version} on {now}",
    ]
    if ctx.source_dlm_path is not None:
        lines.append(f"# Source: {ctx.source_dlm_path}")
    lines.extend(
        [
            f"# dlm_id: {ctx.dlm_id}",
            f"# adapter_version: {ctx.adapter_version}",
            f"# base_model: {ctx.spec.key} (revision {ctx.spec.revision})",
            f"# quant: {ctx.plan.quant}",
            f"# merged: {ctx.plan.merged}",
        ]
    )
    return "\n".join(lines)


# --- stops ----------------------------------------------------------------


def _resolve_stops(adapter_dir: Path, template_row: DialectTemplate) -> tuple[str, ...]:
    """Union of dialect defaults + EOS/pad from the adapter tokenizer.

    Per Sprint 12b tokenizer contract (audit F06): added special tokens
    from the adapter tokenizer become additional stops. Without this,
    a pad-token-grown model emits `<|pad|>` indefinitely.
    """
    merged: list[str] = list(template_row.default_stops)
    merged.extend(template_row.extra_stop_hints)

    adapter_stops = _read_adapter_stops(adapter_dir)
    for tok in adapter_stops:
        if tok and tok not in merged:
            merged.append(tok)

    # De-dupe while preserving order.
    seen: set[str] = set()
    unique: list[str] = []
    for tok in merged:
        if tok not in seen:
            seen.add(tok)
            unique.append(tok)
    return tuple(unique)


def _read_adapter_stops(adapter_dir: Path) -> list[str]:
    """Pull `eos_token` + added-tokens from the adapter tokenizer config.

    Missing files return `[]` — the caller combines with dialect
    defaults. Malformed JSON raises `ModelfileError`.
    """
    cfg_path = adapter_dir / "tokenizer_config.json"
    if not cfg_path.exists():
        return []
    try:
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ModelfileError(
            f"adapter tokenizer_config.json at {cfg_path} is unreadable: {exc}"
        ) from exc

    stops: list[str] = []
    eos = cfg.get("eos_token")
    if isinstance(eos, str) and eos:
        stops.append(eos)
    elif isinstance(eos, dict) and isinstance(eos.get("content"), str):
        stops.append(eos["content"])

    # Sprint 07 added-tokens (the `<|pad|>` fallback path): walk
    # `added_tokens_decoder` for content strings flagged as special.
    added = cfg.get("added_tokens_decoder") or {}
    if isinstance(added, dict):
        for entry in added.values():
            if isinstance(entry, dict) and entry.get("special") is True:
                content = entry.get("content")
                if isinstance(content, str):
                    stops.append(content)
    return stops


# --- template block -------------------------------------------------------


def _build_template_block(template_row: DialectTemplate) -> str:
    """Emit the Modelfile TEMPLATE directive with the Go template body.

    Ollama accepts triple-double-quoted strings for multi-line TEMPLATE
    values. We assume no literal triple-double-quote appears inside the
    Go template (ours don't).
    """
    body = template_row.read_template()
    return f'TEMPLATE """{body}"""'


# --- parameters -----------------------------------------------------------


def _build_param_lines(
    *,
    stops: tuple[str, ...],
    temperature: float,
    top_p: float,
) -> list[str]:
    """Emit the `PARAMETER stop ...` + defaults block."""
    lines: list[str] = []
    for stop in stops:
        lines.append(f"PARAMETER stop {json.dumps(stop)}")
    lines.append(f"PARAMETER temperature {temperature}")
    lines.append(f"PARAMETER top_p {top_p}")
    return lines


# --- system + license -----------------------------------------------------


def _build_system_line(system_prompt: str | None) -> str | None:
    """Shell-escaped `SYSTEM "..."` directive, or `None` when no prompt.

    Ollama treats SYSTEM as a quoted string; embedded `"` in the user's
    prompt would break parsing (or inject directives). `shlex.quote`
    produces a POSIX-safe literal; we strip the outer shell-quoting
    and re-quote for Modelfile grammar by using JSON encoding, which
    handles all escape cases uniformly.
    """
    if system_prompt is None:
        return None
    stripped = system_prompt.strip()
    if not stripped:
        return None
    # JSON encoding escapes `"`, `\n`, `\\` correctly for a Modelfile
    # string literal — same quoting rules as Python string literals.
    _ = shlex.quote  # referenced for provenance; JSON is what we use
    return f"SYSTEM {json.dumps(stripped)}"


def _build_license_line(spec: BaseModelSpec) -> str | None:
    if not spec.license_spdx:
        return None
    return f"LICENSE {json.dumps(spec.license_spdx)}"
