"""VL Ollama Modelfile rendering."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from dlm.base_models import BASE_MODELS
from dlm.export.ollama.errors import ModelfileError
from dlm.export.ollama.vl_modelfile import (
    _VL_DEFAULT_TEMPERATURE,
    _VL_DEFAULT_TOP_P,
    _VL_TEMPLATE_BODY,
    VlModelfileContext,
    _fallback_stops_for,
    _vl_template_row,
    render_vl_modelfile,
)
from dlm.export.plan import ExportPlan

_QWEN_VL_SPEC = BASE_MODELS["qwen2-vl-2b-instruct"]
_PALIGEMMA_SPEC = BASE_MODELS["paligemma-3b-mix-224"]
_INTERNVL_SPEC = BASE_MODELS["internvl2-2b"]
_MISTRAL_VL_SPEC = BASE_MODELS["mistral-small-3.1-24b-instruct"]


def _adapter_dir(tmp_path: Path, **extra: object) -> Path:
    adapter = tmp_path / "adapter"
    adapter.mkdir(exist_ok=True)
    cfg = {
        "eos_token": "<|im_end|>",
        "added_tokens_decoder": {
            "50265": {"content": "<|vision_pad|>", "special": True},
        },
        **extra,
    }
    (adapter / "tokenizer_config.json").write_text(json.dumps(cfg), encoding="utf-8")
    return adapter


def _ctx(
    tmp_path: Path,
    *,
    spec: object | None = None,
    merged: bool = False,
    adapter: Path | None = None,
    adapter_gguf_name: str | None = "adapter.gguf",
    training_sequence_len: int | None = None,
    system_prompt: str | None = None,
    override_temperature: float | None = None,
    override_top_p: float | None = None,
) -> VlModelfileContext:
    return VlModelfileContext(
        spec=_QWEN_VL_SPEC if spec is None else spec,
        plan=ExportPlan(quant="Q4_K_M", merged=merged),
        adapter_dir=adapter or _adapter_dir(tmp_path),
        base_gguf_name="base.Q4_K_M.gguf",
        adapter_gguf_name=adapter_gguf_name,
        dlm_id="01VLTEST",
        adapter_version=4,
        system_prompt=system_prompt,
        source_dlm_path=tmp_path / "doc.dlm",
        dlm_version="test",
        training_sequence_len=training_sequence_len,
        override_temperature=override_temperature,
        override_top_p=override_top_p,
    )


class TestFallbackStops:
    @pytest.mark.parametrize(
        ("spec", "expected"),
        [
            (_PALIGEMMA_SPEC, ("<eos>",)),
            (_QWEN_VL_SPEC, ("<|im_end|>", "<|endoftext|>")),
            (_INTERNVL_SPEC, ("<|im_end|>", "<|endoftext|>", "</s>")),
            (_MISTRAL_VL_SPEC, ("</s>", "[INST]")),
        ],
    )
    def test_known_architectures_have_expected_fallback_stops(
        self, spec: object, expected: tuple[str, ...]
    ) -> None:
        assert _fallback_stops_for(spec.architecture) == expected

    def test_unknown_architecture_uses_default_union(self) -> None:
        assert _fallback_stops_for("UnknownVLArch") == ("<|im_end|>", "<eos>")

    def test_vl_template_row_reflects_family_defaults(self) -> None:
        row = _vl_template_row(_MISTRAL_VL_SPEC.architecture)
        assert row.default_stops == ("</s>", "[INST]")
        assert row.default_temperature == pytest.approx(_VL_DEFAULT_TEMPERATURE)
        assert row.default_top_p == pytest.approx(_VL_DEFAULT_TOP_P)
        assert row.template_path == Path("/dev/null")


class TestRenderVlModelfile:
    def test_renders_header_template_and_adapter_lines(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(_ctx(tmp_path, training_sequence_len=8192))

        assert "# Generated by dlm test on " in text
        assert "# Source: " in text
        assert "# dlm_id: 01VLTEST" in text
        assert "# adapter_version: 4" in text
        assert f"# base_model: {_QWEN_VL_SPEC.key}" in text
        assert "FROM ./base.Q4_K_M.gguf" in text
        assert "ADAPTER ./adapter.gguf" in text
        assert f'TEMPLATE """{_VL_TEMPLATE_BODY}"""' in text
        assert "PARAMETER num_ctx 8192" in text
        assert 'LICENSE "Apache-2.0"' in text
        assert text.endswith("\n")

    def test_merged_export_omits_adapter_line(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(_ctx(tmp_path, merged=True, adapter_gguf_name=None))

        assert "FROM ./base.Q4_K_M.gguf" in text
        assert "ADAPTER " not in text

    def test_vl_defaults_are_conservative_and_overridable(self, tmp_path: Path) -> None:
        default_text = render_vl_modelfile(_ctx(tmp_path))
        override_text = render_vl_modelfile(
            _ctx(tmp_path, override_temperature=0.55, override_top_p=0.77)
        )

        assert f"PARAMETER temperature {_VL_DEFAULT_TEMPERATURE}" in default_text
        assert f"PARAMETER top_p {_VL_DEFAULT_TOP_P}" in default_text
        assert "PARAMETER temperature 0.55" in override_text
        assert "PARAMETER top_p 0.77" in override_text

    def test_training_sequence_len_is_capped_to_spec_context(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(_ctx(tmp_path, training_sequence_len=999_999))

        assert f"PARAMETER num_ctx {_QWEN_VL_SPEC.context_length}" in text
        assert "PARAMETER num_ctx 999999" not in text

    def test_system_prompt_is_json_escaped(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(
            _ctx(tmp_path, system_prompt='look closely"\nPARAMETER hacked yes')
        )

        system_lines = [line for line in text.splitlines() if line.startswith("SYSTEM ")]
        assert len(system_lines) == 1
        assert '\\"' in system_lines[0]
        assert "\\n" in system_lines[0]
        assert not any(line.startswith("PARAMETER hacked") for line in text.splitlines())

    def test_blank_system_prompt_is_omitted(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(_ctx(tmp_path, system_prompt="  \n "))

        assert "SYSTEM " not in text


class TestVlStopsFromAdapter:
    def test_family_defaults_and_adapter_special_tokens_are_merged(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(_ctx(tmp_path))

        assert 'PARAMETER stop "<|im_end|>"' in text
        assert 'PARAMETER stop "<|endoftext|>"' in text
        assert 'PARAMETER stop "<|vision_pad|>"' in text

    def test_dedups_eos_when_adapter_matches_family_default(self, tmp_path: Path) -> None:
        text = render_vl_modelfile(_ctx(tmp_path))

        assert text.count('PARAMETER stop "<|im_end|>"') == 1

    def test_missing_tokenizer_config_uses_family_defaults(self, tmp_path: Path) -> None:
        adapter = tmp_path / "bare"
        adapter.mkdir()

        text = render_vl_modelfile(_ctx(tmp_path, adapter=adapter, spec=_PALIGEMMA_SPEC))

        assert 'PARAMETER stop "<eos>"' in text

    def test_dict_eos_content_is_respected(self, tmp_path: Path) -> None:
        adapter = _adapter_dir(tmp_path, eos_token={"content": "<|my_vl_eos|>"})

        text = render_vl_modelfile(_ctx(tmp_path, adapter=adapter))

        assert 'PARAMETER stop "<|my_vl_eos|>"' in text

    def test_malformed_tokenizer_config_raises(self, tmp_path: Path) -> None:
        adapter = tmp_path / "broken"
        adapter.mkdir()
        (adapter / "tokenizer_config.json").write_text("{not json", encoding="utf-8")

        with pytest.raises(ModelfileError, match="unreadable"):
            render_vl_modelfile(_ctx(tmp_path, adapter=adapter))
